# CMake generated Testfile for 
# Source directory: C:/Users/t-ahmeb/Downloads/caffe-cmake/caffe-cmake/src/caffe/test
# Build directory: C:/Users/t-ahmeb/Downloads/caffe-cmake/caffe-cmake/build-final/src/caffe/test
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(test_argmax_layer "test_argmax_layer.test")
ADD_TEST(test_benchmark "test_benchmark.test")
ADD_TEST(test_blob "test_blob.test")
ADD_TEST(test_caffe_main "test_caffe_main.test")
ADD_TEST(test_common "test_common.test")
ADD_TEST(test_concat_layer "test_concat_layer.test")
ADD_TEST(test_convolution_layer "test_convolution_layer.test")
ADD_TEST(test_data_layer "test_data_layer.test")
ADD_TEST(test_eltwise_layer "test_eltwise_layer.test")
ADD_TEST(test_euclidean_loss_layer "test_euclidean_loss_layer.test")
ADD_TEST(test_filler "test_filler.test")
ADD_TEST(test_flatten_layer "test_flatten_layer.test")
ADD_TEST(test_hdf5data_layer "test_hdf5data_layer.test")
ADD_TEST(test_hdf5_output_layer "test_hdf5_output_layer.test")
ADD_TEST(test_hinge_loss_layer "test_hinge_loss_layer.test")
ADD_TEST(test_im2col_layer "test_im2col_layer.test")
ADD_TEST(test_image_data_layer "test_image_data_layer.test")
ADD_TEST(test_inner_product_layer "test_inner_product_layer.test")
ADD_TEST(test_lrn_layer "test_lrn_layer.test")
ADD_TEST(test_math_functions "test_math_functions.test")
ADD_TEST(test_maxpool_dropout_layers "test_maxpool_dropout_layers.test")
ADD_TEST(test_memory_data_layer "test_memory_data_layer.test")
ADD_TEST(test_multinomial_logistic_loss_layer "test_multinomial_logistic_loss_layer.test")
ADD_TEST(test_net "test_net.test")
ADD_TEST(test_neuron_layer "test_neuron_layer.test")
ADD_TEST(test_platform "test_platform.test")
ADD_TEST(test_pooling_layer "test_pooling_layer.test")
ADD_TEST(test_power_layer "test_power_layer.test")
ADD_TEST(test_protobuf "test_protobuf.test")
ADD_TEST(test_random_number_generator "test_random_number_generator.test")
ADD_TEST(test_sigmoid_cross_entropy_loss_layer "test_sigmoid_cross_entropy_loss_layer.test")
ADD_TEST(test_softmax_layer "test_softmax_layer.test")
ADD_TEST(test_softmax_with_loss_layer "test_softmax_with_loss_layer.test")
ADD_TEST(test_split_layer "test_split_layer.test")
ADD_TEST(test_stochastic_pooling "test_stochastic_pooling.test")
ADD_TEST(test_syncedmem "test_syncedmem.test")
ADD_TEST(test_tanh_layer "test_tanh_layer.test")
ADD_TEST(test_threshold_layer "test_threshold_layer.test")
ADD_TEST(test_upgrade_proto "test_upgrade_proto.test")
ADD_TEST(test_util_blas "test_util_blas.test")
